### ISSUE TITLE
Does this theme support transparency?

### ISSUE THREAD

**Issue by LC0117** [rmehri01/onenord.nvim#11]
I'm using the same theme for iTerm, which supports transparency. I think it's a good feature to be considered.

**Comment by rmehri01** [comment]
Hi! There's an option for `disable.background` that does this right now, although maybe it would be better if I renamed it to `transparent`. Also if you have any suggestions for how it should look in transparent mode then let me know since I'm not really sure how it should look like.

**Comment by LC0117** [comment]
Thanks for the tip! That's good enough.
