### ISSUE TITLE
Feature request - light mode

### ISSUE THREAD

**Issue by dakennguyen** [rmehri01/onenord.nvim#15]
Hi, I love the combination of one and nord theme. Nord theme doesn't support light mode, but one theme has light mode. Maybe this is too much to ask but what do you think about having a light mode for onenord? At first, we can build it from onelight's colors, and then create our own light version of nord later where we see fit. 

If you are interested, I'm willing to give a hand if you need any help 😄

**Comment by rmehri01** [comment]
Hi again! I think that's a good idea, I'll try out some colors and see if I can get something that fits well. Theoretically it shouldn't be too hard to do since I just need to make another color palette but I'd appreciate your help with testing it out later 😄

**Comment by dakennguyen** [comment]
awesome, thank you!! I'll wait for your update then

**Comment by rmehri01** [comment]
Alright, I just changed some colors around and here is what I have so far. I think it's not too bad but some of the contrast seems a bit off. I don't have much experience with light mode themes so what do you think:

<img width="1542" alt="Screen Shot 2021-12-04 at 11 27 53 AM" src="https://user-images.githubusercontent.com/52933714/144722188-71fb437f-da44-4fe8-94ef-bd01e042f54b.png">

<img width="1542" alt="Screen Shot 2021-12-04 at 11 28 03 AM" src="https://user-images.githubusercontent.com/52933714/144722194-3871d7a0-1d68-4b02-a5bc-4950b941f0b6.png">

**Comment by dakennguyen** [comment]
I think it looks nice!!! But not sure if the yellow is too bright or not 🤔  Would you mind pushing the branch so I can further test it on some of my languages?

**Comment by rmehri01** [comment]
Sure, let me clean it up a bit first and then I'll make a pr for it and tag you. Yeah I think that might be a good idea, I'll try it out after!

**Comment by rmehri01** [comment]
Hi! I've just been using `:colorscheme onenord` and `:colorscheme onenordlight`, but I think your way is better since there's only 2 themes. I just pushed a change for it!

**Comment by VKondakoff** [comment]
Thanks, works like a charm! 👍
