### ISSUE TITLE
Add option to use "undercurl" for diagnostic "underline" errors

### ISSUE THREAD

**Issue by kristijanhusak** [rmehri01/onenord.nvim#17]
Hi,

it would be great to have a way to set "undercurl" instead of "underline" for the Lsp diagnostic errors, without overriding the colors manually. Currently it's [hardcoded](https://github.com/rmehri01/onenord.nvim/blob/main/lua/onenord/theme.lua#L485). Like a single option on the setup or something like that.

What do you think?

**Comment by rmehri01** [comment]
Hi, sure I could add a config option in the setup for it! Do you think it should apply to errors, warnings, information, and hints together or be separate? Also I think I'll make it so you can just change it to any style or combination like bold, italic, etc.

**Comment by kristijanhusak** [comment]
For me, having single option for all of them would do the trick, but if you want to offer more flexibility, that's even better. I'm ok with either.

**Comment by rmehri01** [comment]
Alright, I added a convenient option that does all 4 with `styles.diagnostics` and also a way to overwrite just the styles of any highlight group with `custom_styles`. Check it out and let me know what you think!

**Comment by kristijanhusak** [comment]
Works like a charm, thanks!
