### ISSUE TITLE
Installation issue with Plug

### ISSUE THREAD

**Issue by hepplerj** [rmehri01/onenord.nvim#2]
A fairly minor issue, and it could be something in my own setup that's causing this, but it seems that using `Plug` defaults to a branch named `master` rather than `main`. So, to install, users may need to use:

```
Plug 'rmehri01/onenord.nvim', { 'branch': 'main' }
```

Might be worth mentioning in the README. 

(And thanks for putting this together! It looks fantastic.)

**Comment by rmehri01** [comment]
Ah I see, I didn't know about this. I'll add it to the readme, thanks!
