### ISSUE TITLE
Change QuickFixLine highlight

### ISSUE THREAD

**Issue by dakennguyen** [rmehri01/onenord.nvim#20]
I cannot distinguish selected quickfix line with the others
![Screen Shot 2021-12-10 at 13 58 05](https://user-images.githubusercontent.com/18320285/145530999-50374530-ddf9-47c6-8acd-ee43ef4af00e.png)

Currently I have this line in my config `QuickFixLine = { style = 'italic' }`, but I think we should have a default value
![Screen Shot 2021-12-10 at 13 59 29](https://user-images.githubusercontent.com/18320285/145531168-35573359-eef1-44bd-9732-320023292a7c.png)

**Comment by rmehri01** [comment]
Oh, sorry about that, I think that looks better! I think adding the bold and background might help too, what do you think:

![image](https://user-images.githubusercontent.com/52933714/145533157-eef3c14a-d44d-49cd-8f53-11bd88015e77.png)

**Comment by dakennguyen** [comment]
yeah cool, that looks good to me 😄
