### ISSUE TITLE
FR: change the appearance of non current windows (in split view)

### ISSUE THREAD

**Issue by VKondakoff** [rmehri01/onenord.nvim#21]
Hi!

Currently the only way to distinguish between current and non current window in split view is setting a special color to a statusline when it's window is non current.

<img width="628" alt="Снимок экрана 2021-12-10 в 14 18 28" src="https://user-images.githubusercontent.com/230824/145566412-a19fd992-1c6d-4433-9922-d89c8a9f2c92.png">

As far as I see there are other ways to do this. What about adding an options:
1. Use alt background color when window is non current (dim the color a little)
2. Disable the cursor line highlighting when window is non current

Any other ideas?

I'm pretty sure this may be a great QoL enhancement. What do you think?

**Comment by rmehri01** [comment]
Hi, I think this is a good config option to have! I've been trying out the alternate background color, and so far it looks like this:

<img width="1542" alt="Screen Shot 2021-12-10 at 9 30 43 AM" src="https://user-images.githubusercontent.com/52933714/145616547-8286d92c-b560-48de-8d1c-6bc492bf9625.png">

Unfortunately, I can't seem to find a way to change the `SignColumn` and `CursorLine` individually when the window is non current. Do you know of any?

**Comment by VKondakoff** [comment]
Hey, this looks quite good. I don't really know a way to change `SignColumn` and `CursorLine` when window is non active - this was just a quick idea... But setting the bg to cursor line color seems quite good workaround...

**Comment by rmehri01** [comment]
No problem, yeah I think this could be included for now and I'll see if I can do anything about the `SignColumn`!

**Comment by rmehri01** [comment]
Oh, I just changed it to none and it worked!

<img width="1542" alt="Screen Shot 2021-12-10 at 10 09 53 AM" src="https://user-images.githubusercontent.com/52933714/145621472-a7bccdd8-e877-452c-9699-c8c2179ec131.png">

**Comment by VKondakoff** [comment]
Ha-ha! 👍

**Comment by rmehri01** [comment]
Thanks again for the suggestion!
