### ISSUE TITLE
Support tree-sitter-markdown highlight groups

### ISSUE THREAD

**Issue by jose-elias-alvarez** [rmehri01/onenord.nvim#22]
[MDeiml/tree-sitter-markdown](https://github.com/MDeiml/tree-sitter-markdown) is a new Markdown parser for Treesitter that (among other things) improves speed and uses Treesitter to highlight embedded code blocks.The parser is still experimental, but it's already a big improvement over traditional syntax highlighting, so it would be great to have support for it here. I asked the author on Reddit how colorschemes can support it, and they said:

> They would need to add colors for the highlight groups TSTitle, TSLiteral, TSEmphasis, TSStrong, TSURI, TSTextReference, TSPunctSpecial and TSStringEscape.

For reference, [this commit](https://github.com/catppuccin/nvim/commit/22b34eb9f93430bc010dee1523743b62cd2700fc) shows how Catpuccin implemented support.

**Comment by rmehri01** [comment]
Thanks for letting me know and for the extra details! This looks really nice, I really like the highlighting in code blocks. These groups already exist so I think it looks decent now but I added some colors for `TSStrong` and `TSEmphasis`, what do you think:

<img width="1542" alt="Screen Shot 2021-12-15 at 10 00 26 PM" src="https://user-images.githubusercontent.com/52933714/146316740-4b5126f6-f793-4fc8-b2b6-a9187ce3990a.png">

**Comment by jose-elias-alvarez** [comment]
Looks great! I should have been more specific about what seemed to be missing, and bold / italic colors make a big difference. I also wonder if a different color for link titles would help. Here's a couple of links with Treesitter:

<img width="540" alt="Screen Shot 2021-12-16 at 12 56 15 PM" src="https://user-images.githubusercontent.com/54108223/146423954-b969a41c-9a2a-419a-a1b7-369deedc21ca.png">

And without:

<img width="540" alt="Screen Shot 2021-12-16 at 12 58 10 PM" src="https://user-images.githubusercontent.com/54108223/146424190-f2d507e5-60db-49e1-a048-a155f378abd1.png">

The latter seems a bit easier to parse, but what do you think?

**Comment by rmehri01** [comment]
Ah I see, yeah I like the cyan more! Do you have any other suggestions for the markdown colors, either with or without Treesitter? I just have those 3 changes so far:

<img width="1542" alt="Screen Shot 2021-12-16 at 10 12 34 AM" src="https://user-images.githubusercontent.com/52933714/146426120-a676178c-1aec-4198-bd84-4bc873ff9339.png">

**Comment by jose-elias-alvarez** [comment]
Looks great as-is IMO!
