### ISSUE TITLE
Can No longer Override With Custom Highlights

### ISSUE THREAD

**Issue by cjhead** [rmehri01/onenord.nvim#24]
Hello and thank you very much for this awesome color scheme! It's easy to use and looks great! I'm not sure when exactly it happened or what caused it, but my custom highlights no longer override the stock ones. Here's my current config file. I know it loads fine and every part of the config works _except_ for the custom highlights. I'm sure it's something I'm doing. Thank you in advance!

```lua
local colors = require('onenord.colors')

require('onenord').setup({
  theme = "dark",
  borders = true,
  face_nc = true,
  styles = {
    comments = "italic",
    strings = "italic",
    keywords = "italic",
    functions = "italic",
    variables = "NONE",
    diagnostics = "underline",
  },
  disable = {
    background = false,
    cursorline = false,
    eob_lines = true,
  },
  custom_highlights = {

    -- NvimTree
    NvimTreeOpenedFile = { fg = colors.diff_add, style = 'bold' },

    -- Local Syntax
    Conditional = { fg = colors.blue },
    Number = { fg = colors.purple },
    Operator = { fg = colors.dark_blue },
    Statement = { fg = colors.fg },
    MatchParen = { fg = colors.light_purple, bg = colors.none, style = 'bold' },

    -- TreeSitter
    TSBoolean = { fg = colors.yellow },

    -- BarBar
    BufferCurrentMod = { fg = colors.purple, bg = colors.bg, style = 'bold' },
    BufferVisibleMod = { fg = colors.purple, bg = colors.bg, style = 'bold' },
    BufferInactiveMod = { fg = colors.purple, bg = colors.bg, style = 'bold' },
  },
})
```

**Comment by cjhead** [comment]
I also tried changing the order in which the theme was loaded within packer itself and even tried loading the config with an explicit `after = nvim-treesitter` to see if it would affect anything and it didn't.

**Comment by rmehri01** [comment]
Hi, thanks for the kind words, I'm glad you like it! Sorry, this is actually my fault, I messed it up when making some config changes. I think that the latest commit should fix it but let me know if you run into any problems.

**Comment by cjhead** [comment]
> Hi, thanks for the kind words, I'm glad you like it! Sorry, this is actually my fault, I messed it up when making some config changes. I think that the latest commit should fix it but let me know if you run into any problems.

Yep! Everything works! Thank you so much!

**Comment by rmehri01** [comment]
No problem!

**Comment by rmehri01** [comment]
#30 has a breaking change so that you have to do `require('onenord.colors').load()` instead!
