### ISSUE TITLE
Set custom highlights for jsdoc tags?

### ISSUE THREAD

**Issue by zeitchef** [rmehri01/onenord.nvim#25]
I'd like to change the colors of my jsdoc tags (eg. @param in purple to some other color) - is there a way to do this? Or can I override Treesitter somehow to achieve this?

![Screen Shot 2021-12-28 at 12 15 41](https://user-images.githubusercontent.com/6670659/147560792-66fb4fdf-6e32-433b-a2b9-b2bd7f49638c.jpg)

**Comment by rmehri01** [comment]
Hi, I think that the [treesitter playground](https://github.com/nvim-treesitter/playground) lets you see which groups are currently applied with `:TSHighlightCapturesUnderCursor`. It gives me the following:

![image](https://user-images.githubusercontent.com/52933714/147599052-90ceaa4e-ed1b-4861-b3a5-6e63cc7f55c0.png)

So it looks like you would have to change `TSKeyword`!

**Comment by zeitchef** [comment]
Awesome. I had never heard of TS Playground, that's so helpful! Thanks again.

**Comment by rmehri01** [comment]
No problem! Yeah it's been really helpful for me 😁
