### ISSUE TITLE
All blue blackground color

### ISSUE THREAD

**Issue by JimmyMinhLee** [rmehri01/onenord.nvim#27]
I just installed the colorscheme, but when I change it over, it gives me this: 

<img width="1440" alt="Screen Shot 2022-01-02 at 1 05 49 AM" src="https://user-images.githubusercontent.com/46268173/147871268-b5541843-729e-4cdb-bd05-001153b8fba1.png">

My complete `init.vim` file is as such: 

<img width="1440" alt="Screen Shot 2022-01-02 at 1 06 10 AM" src="https://user-images.githubusercontent.com/46268173/147871272-fdcd27bf-eb18-4017-b314-137a3cff8664.png">

Apologies if this isn't the right place to put it - brand new to the `nvim` community, any help would be greatly appreciated!

**Comment by JimmyMinhLee** [comment]
Realizing this probably isn't the best place to put it - will close and move to discussions instead.

**Comment by rmehri01** [comment]
Either works, I just enabled discussions if you want to use it!

**Comment by rmehri01** [comment]
As for the actual issue, I'm not sure how to reproduce it. Are there any specific steps you took, or is it just like that on startup?

**Comment by JimmyMinhLee** [comment]
It was like that on startup which is a bummer. ): I really enjoyed the colorscheme; others like dracula, and everforest don't do the same thing for me.

**Comment by rmehri01** [comment]
Oh I see, are you using the default terminal app on MacOS because the same happens to me there but not in other terminal emulators like kitty and alacritty. I'll try to figure this out soon!

**Comment by JimmyMinhLee** [comment]
Yes! I think this may just be a problem with the default terminal - thanks for being so responsive. (:

**Comment by rmehri01** [comment]
No problem! I think what is happening is that I am using a dark blue color for the normal background and the default terminal uses only 16 colors so the closest is that blue you get. Maybe try out a different terminal emulator, we have themes for those too in the `extras` folder if you want them 😄

**Comment by JimmyMinhLee** [comment]
Will do - do you have any recommendations on an emulator to switch over to? I've thought about using iTerm2 in the past, but I just liked having an out of the box application

**Comment by rmehri01** [comment]
If you want it to work out of the box, I'd say iterm2 is a good way to go! I used it for a while and then switched to Kitty since it feels more snappy on my machine but everyone has different preferences :)
