### ISSUE TITLE
"E28: No such highlight group name: markdownError" since 0.6.1

### ISSUE THREAD

**Issue by zeitchef** [rmehri01/onenord.nvim#29]
Hi, me again :) Not sure if this is a theme error, but since updating to Neovim 0.6.1 I'm getting this error when running `checkhealth`. I'm able to get rid of the error when setting this myself, but perhaps this should be set in the theme?

**Comment by rmehri01** [comment]
Hi again! I don't seem to get anything related to the theme when using `:checkhealth`, is there something I need to enable to see it?

**Comment by zeitchef** [comment]
Sorry, tracked this down to another plugin. Don't mind me!

**Comment by rmehri01** [comment]
All good!

**Comment by grimm26** [comment]
> Sorry, tracked this down to another plugin. Don't mind me!

What plugin?!?! @rmehri01

**Comment by rmehri01** [comment]
I'm not sure, I think you'd have to ask @zeitchef :)
