### ISSUE TITLE
LuaLine Issues

### ISSUE THREAD

**Issue by shMorganson** [rmehri01/onenord.nvim#3]
My lualine with onenord appears to be a bit difficult to read and doesn't seem to look like the one in the screen shot of the theme.
![Screen Shot 2021-11-01 at 12 49 40 PM](https://user-images.githubusercontent.com/59580484/139709480-980157fa-85ae-452e-ac14-11a45ec3a826.png)

**Comment by rmehri01** [comment]
Hey, I just pushed a commit so hopefully that is better! The lualine config I use is from LunarVim: https://github.com/LunarVim/LunarVim/tree/rolling/lua/lvim/core/lualine.

**Comment by shMorganson** [comment]
Awesome! Thanks!! Again, this theme is great.
