### ISSUE TITLE
Add new color 'dark_gray' (#3B4252)

### ISSUE THREAD

**Issue by zeitchef** [rmehri01/onenord.nvim#33]
Hey there, me again :) I'd love a couple more grays from the Nord palette, specifically #3b4252 as either `dark_gray` or maybe `bg_light`. What do you think?

**Comment by zeitchef** [comment]
Sorry! I should have noticed `onenord.float`. Closing now.

**Comment by rmehri01** [comment]
Hi! No problem, perhaps they don't have the best names but there are a few variations of gray and the blueish gray colors used for selection and comments if those work 😅
