### ISSUE TITLE
Missing docs: How to use the onenord.yaml config

### ISSUE THREAD

**Issue by lvstb** [rmehri01/onenord.nvim#34]
Im not sure on how and where to use the onenord.yaml file included in the extras. I dont even know to which plugin/tool this file belongs.

**Comment by rmehri01** [comment]
Hi! As mentioned in the [extras section](https://github.com/rmehri01/onenord.nvim#extras), these are color configs for other tools and you should refer to their respective documentation to set them up. 

In the case of `onenord.yaml`, it is for Alacritty: https://github.com/alacritty/alacritty/wiki/Color-schemes. Maybe I could link each of the extras to the file they use if you think that would help?
