### ISSUE TITLE
feature request: inverse matches

### ISSUE THREAD

**Issue by quantum-booty** [rmehri01/onenord.nvim#36]
In [srcery-vim](https://github.com/srcery-colors/srcery-vim) there is an option to inverse the colour of matches and match parenthesis of treesitter-highlight module or a / search:
![image](https://user-images.githubusercontent.com/28958399/167930557-973a7486-a862-41aa-8ab3-1da65c55b333.png)
![image](https://user-images.githubusercontent.com/28958399/167930382-60eaaae1-360f-4770-8bdf-7d1c80b4bd04.png)

Could you please add a similar feature to onenord? Because I think this can improve visibility of these matches.

**Comment by rmehri01** [comment]
I think this commit should do it!
