### ISSUE TITLE
Highlights overriding not working

### ISSUE THREAD

**Issue by manuelcattelan** [rmehri01/onenord.nvim#38]
Heya! Thanks for the lovely plugin, very pleasing and a great improvement from the original nord colorscheme. I was trying to change the way highlights are displayed on cursor hold the same way you explained in #26:

![Schermata 2022-05-25 alle 16 29 09](https://user-images.githubusercontent.com/91598275/170287046-54ac39e0-9fce-424e-8417-74d6537f2c66.png)

But the overriding doesn't seem to be applied:

![Schermata 2022-05-25 alle 16 29 19](https://user-images.githubusercontent.com/91598275/170287131-d5546fb7-3820-408b-984c-c9e87de23f2f.png)

I imported colors with ```local colors = require('onenord.colors')``` but I'm not 100% sure that's how it works, could you help me?

**Comment by rmehri01** [comment]
Haha no problem, maybe you read an older commit because that is how it was before there were themes!
