### ISSUE TITLE
HTML custom elements

### ISSUE THREAD

**Issue by joeveiga** [rmehri01/onenord.nvim#41]
Hello 👋 ! Is there a way to make html custom elements look the same as regular html elements? Also attributes as well.
Thanks!

![image](https://user-images.githubusercontent.com/19226858/173605351-2e1a2352-8cc2-4aff-a744-d34ba275169a.png)

**Comment by rmehri01** [comment]
Hi! I think if you use treesitter highlighting then it will be much more consistent, even for custom elements:

<img width="518" alt="image" src="https://user-images.githubusercontent.com/52933714/173699346-ec5dac9b-8ddf-4a39-adf0-8b2e590e5f38.png">

I'm not sure about the normal regex based highlighting, I'll look into it some more and see if I can make it more consistent if you'd like :)

**Comment by joeveiga** [comment]
Thanks! I have treesitter hl disabled cause it didn't look great with the regular nord theme. It also had some performance issues at the time. I'll enable it and check it out!

Either way it'd be a good idea IMO to fix custom elements/attributes for regular regex hl. Nord does alright, maybe you can take a peak and see how they do it, if you have the chance 😉

**Comment by rmehri01** [comment]
Thanks for the quick reply! I tried to change a few things but unfortunately it counts the delimiters and the `[...]` as both the same highlight groups so they can either both be blue or both dark blue:

<img width="546" alt="image" src="https://user-images.githubusercontent.com/52933714/173702149-b4a7ec1c-080b-42d7-8fc9-beed741ecd8d.png">

Still seems like an improvement to me though, what do you think?

**Comment by joeveiga** [comment]
Definitely much better than what I had. Awesome! ✌️

**Comment by rmehri01** [comment]
Alright thanks! Feel free to give it a try and reopen if you have any other concerns :)
