### ISSUE TITLE
Colors too dark for it be "Nord" themed in Nvim

### ISSUE THREAD

**Issue by dylode** [rmehri01/onenord.nvim#44]
Hi there,

I'm just a beginner trying to setup nvim. I have installed your theme but for me the colors feel to dark:

![image](https://user-images.githubusercontent.com/78496445/182859253-c994819a-9da1-4738-8f55-9456f1a97aae.png)

I'm using Alacritty, I use the same background color / theme you provide and there the blue feels good, like the nord theme. However if you look at nvim it's too dark. I have explicitly set the background hex color to same as in Alacritty but they are not the same. What am I missing?

**Comment by dylode** [comment]
Alright I have switched to Kitty terminal and there the colors are fine. I'm fine to switch but I leave this issue open maybe someone will know why the colors are different in Alacritty

**Comment by rmehri01** [comment]
Hi! That's strange, this is what a clean install of Alacritty looks like for me:

<img width="1570" alt="Screen Shot 2022-08-04 at 1 45 04 PM" src="https://user-images.githubusercontent.com/52933714/182949229-6ecfb9e0-737f-4b05-93ff-069f7a462c88.png">

Maybe you have another theme that is overwriting the colors or something? Could you check `:colorscheme` and `:hi` to see if that's the case?

**Comment by dylode** [comment]
> Hi! That's strange, this is what a clean install of Alacritty looks like for me:
> 
> <img alt="Screen Shot 2022-08-04 at 1 45 04 PM" width="1570" src="https://user-images.githubusercontent.com/52933714/182949229-6ecfb9e0-737f-4b05-93ff-069f7a462c88.png">
> 
> Maybe you have another theme that is overwriting the colors or something? Could you check `:colorscheme` and `:hi` to see if that's the case?

Hi there. it does not look like something is overriding anything. The same config works with Kitty. 
`:colorscheme` gives back `onenord` and `:hi` a lot of stuff. I checked some of the highlights and they are the same as in my highlight overrides.  

I have my dotfiles pushed here: https://github.com/dylode/dotfiles would appreciate it if you can check it out.

**Comment by rmehri01** [comment]
Okay so I tried your dotfiles and I still can't reproduce the issue. This is what a clean install on Alacritty looks like for me:

<img width="1540" alt="image" src="https://user-images.githubusercontent.com/52933714/183266458-af7e07fe-8353-480e-b308-6f8a1eb09f3d.png">

Yeah disabling the background means that it will take the background from your terminal which seems to be the right color in the screenshot you sent but it wont fix the other highlights. 

For `:hi` I should have been more specific, I mean like doing `:hi Normal` for example to check that the background (without `disable.background = true`) is the right hex code.

**Comment by dylode** [comment]
> Okay so I tried your dotfiles and I still can't reproduce the issue. This is what a clean install on Alacritty looks like for me:
> 
> <img alt="image" width="1540" src="https://user-images.githubusercontent.com/52933714/183266458-af7e07fe-8353-480e-b308-6f8a1eb09f3d.png">
> 
> Yeah disabling the background means that it will take the background from your terminal which seems to be the right color in the screenshot you sent but it wont fix the other highlights.
> 
> For `:hi` I should have been more specific, I mean like doing `:hi Normal` for example to check that the background (without `disable.background = true`) is the right hex code.

`Normal         xxx guifg=#C8D0E0 guibg=#2e3440`

It does work correctly when I don't use tmux in Alacritty though. If I remove https://github.com/dylode/dotfiles/blob/main/alacritty/alacritty.yml#L80

**Comment by dylode** [comment]
I have fixed it by adding the following to `tmux.conf`

`set-option -ga terminal-overrides ",xterm-256color:Tc"`
