### ISSUE TITLE
Incorrect colors in Gnome Terminal (and derivates)

### ISSUE THREAD

**Issue by BeTmAsTeR** [rmehri01/onenord.nvim#47]
I don't think it's and upstream problem because this is the only colorscheme that does this.

The highlight color of "empty" character like tabs, are not shown correctly by Gnome Terminal and derivates like Tilix, the color is displayed correctly by other terminal like Alacritty

How to reproduce:
- Lauch nvim with Gnome Terminal (or derivates)
- Add content with tabs
- Move the cursor over the tabs, incorrect color is shown

**tilix:**
![image](https://user-images.githubusercontent.com/761740/189398368-c64f34b1-7143-46cf-bae3-d4a7560799c6.png)
**gnome terminal:**
![image](https://user-images.githubusercontent.com/761740/189398556-a697749c-34f3-48e3-8296-fa17dd5d1338.png)

**alacritty:**
![image](https://user-images.githubusercontent.com/761740/189398788-cd2656cf-b2ef-4b9a-8cf5-8994029a62d2.png)

**Comment by rmehri01** [comment]
Hey! I don't have a Linux machine so I can't test this but it seems kind of strange that it works in other terminals. Is the cursor supposed to match the foreground color of what it is on because I don't think that dark blue color is used anywhere?

**Comment by BeTmAsTeR** [comment]
yes, the color showed by Alacritty is the right one

**Also Konsole is affected**
![image](https://user-images.githubusercontent.com/761740/189443404-1be71888-6e14-46ee-9b71-c20019fc44f3.png)

Switching to a similar colorscheme like nordic solve the problem
**tilix:**
![image](https://user-images.githubusercontent.com/761740/189444892-770e202e-a543-4d51-ae27-175a3e8c1bd2.png)

**Comment by rmehri01** [comment]
Could you try changing the highlights for the `Cursor` group and see if that's what controls it?

**Comment by BeTmAsTeR** [comment]
how?

**Comment by rmehri01** [comment]
Something like `:hi Cursor guifg=red guibg=green` and see if that changes how it looks?

**Comment by BeTmAsTeR** [comment]
nothing changes, both in Alacritty and Tilix

**Comment by BeTmAsTeR** [comment]
Ok, i think i found the issue, it's [IndentBlankline](https://github.com/lukas-reineke/indent-blankline.nvim)

After setting some colors for the plugin groups everything works perfectly, here the docs https://github.com/lukas-reineke/indent-blankline.nvim/blob/master/doc/indent_blankline.txt

The groups are
```
IndentBlanklineChar
IndentBlanklineSpaceChar
IndentBlanklineSpaceCharBlankline
IndentBlanklineContextChar
IndentBlanklineContextSpaceChar
IndentBlanklineContextStart
```

I don't know why Alacritty behaves differently

maybe you can add support

**Comment by rmehri01** [comment]
Oh okay interesting, thanks for looking into it, I'll add those!

**Comment by rmehri01** [comment]
Actually before doing that, I think that these groups by default take from `Whitespace` and `Label` which are gray and purple respectively so I'm curious why the blue is showing up. Do you know what group that is from specifically and can you do `:hi <group>` to get the hex code?

My Indent Blankline groups look like this:

<img width="414" alt="image" src="https://user-images.githubusercontent.com/52933714/190863677-cc4d1794-46d4-43ad-a47d-7d4129984d64.png">

**Comment by BeTmAsTeR** [comment]
here we go, i searched the highlights with telescope, like you did

![image](https://user-images.githubusercontent.com/761740/190926910-f3c2d18f-8482-4e4e-ad2a-6745ae06d4f5.png)

My setup for debug this is pretty simple
NVIM v0.8.0-dev-996-g090370263
Packer as package manager
Onenord and IndentBlankline installed and managed with packer (obviously)

onenord config is the simplest possible:
`require('onenord').setup()`

indentblankline config is the simplest possible:
`require("indent_blankline").setup()`

**Comment by rmehri01** [comment]
Hmm interesting, thanks for sharing. It's strange how I can't seem to reproduce the issue even with this minimal setup but I think maybe that it's getting that blue from the default colorscheme because that's how it looks when I use it. In any case I can add the other highlights if it fixes the issue.

**Comment by rmehri01** [comment]
Can you confirm if this fixes it?

**Comment by BeTmAsTeR** [comment]
almost, the underline is yellow
![image](https://user-images.githubusercontent.com/761740/190929639-ee1eca30-c06b-4a05-aa28-38756915621d.png)

**Comment by rmehri01** [comment]
My bad, I missed that it was also different.

**Comment by BeTmAsTeR** [comment]
fixed!
