### ISSUE TITLE
Getting wrong colors with Alacritty

### ISSUE THREAD

**Issue by tomkcey** [rmehri01/onenord.nvim#48]
Hi,
Your theme looks cool so I'd like to try it. Installation seemed easy enough and there was even mention of plug-and-play with Alacritty. My Alacritty itself has nord palette, but wanted to apply yours to neovim since you cover programming keywords and whatnot, but the color scheme doesn't seem to be applied correctly.

Here are some screenshots. Mostly, it seems to be the background that's having problems. 

![1662817402-s](https://user-images.githubusercontent.com/30733005/189486276-c0e600f7-c7fa-49b0-a94f-629ea14999d8.png)
![1662817469-s](https://user-images.githubusercontent.com/30733005/189486277-dc25b1d8-37d8-49dd-99e8-bf74b9871780.png)
![1662817493-s](https://user-images.githubusercontent.com/30733005/189486278-c92eb9bc-9a07-4288-8cf0-8f5e1dffbd3b.png)
![1662817504-s](https://user-images.githubusercontent.com/30733005/189486279-7866a234-d37d-4863-a3fa-fad46d22f4b2.png)

**Note**: when saving my `plugins.lua` file it did download your package. I'm using Packer.

I tried disabling the background with the disable option in `.setup()` but that didn't seem to work either.

**Comment by rmehri01** [comment]
Hi! That's strange, I'm not sure why this would be the case but it looks kind of like #44, is there some option for true colors that needs to be set?

**Comment by tomkcey** [comment]
Interesting,
The person seems to have an issue with the background and bar colors on a `tmux`'d Alacritty, which is also the case for me. I tried setting the same config mentioned in the last message but haven't had any luck. I didn't restart my system yet but did kill ll my tmux sessions, still without effect. I'll give this another hand tomorrow. Otherwise I'll just reference what you did and essentially debug one by one until I find the culprit. The other colors seem fine, it's really just bckground and bar `bg` colours (`fg` is ok).

You can close this if you'd like. I'll come back and post my solution later.

**Comment by rmehri01** [comment]
Hmm okay interesting, did you get a chance to look into it?

**Comment by tomkcey** [comment]
Nah, except restarting my PC but that had no effect. I'll dig in further another time perhaps. Definitely feel free to close this issue.

**Comment by rmehri01** [comment]
Alright sounds good, thanks!
