### ISSUE TITLE
E185: Cannot find color scheme 'onenord'

### ISSUE THREAD

**Issue by bastienboutonnet** [rmehri01/onenord.nvim#5]
First off thanks a lot for putting this theme together it looks really amazing.

I am running into a somewhat strange issue where Plug seems to have successfully installed `onenord` via the following command: `Plug 'rmehri01/onenord.nvim', { 'branch': 'main' }` but when `colorscheme onenord` gets called i get the following error message from my `init.vim`

`E185: Cannot find color scheme 'onenord'`

I've tried installing and uninstalling a few times, I've installed other plugins in the meantime all work apart from this one.

I'm not sure how to help more with debugging but if you have any ideas I'll be happy to try them.

**Comment by rmehri01** [comment]
Hi, thanks for the kind words! This is really strange, as a disclaimer I don't use Plug but I have tested it with the following setup which seems to work:

`init.vim`:
```vim
call plug#begin('~/.config/nvim/autoload/plugged')
    Plug 'rmehri01/onenord.nvim', { 'branch': 'main' }
call plug#end()

colorscheme onenord
```

I can't really seem to reproduce the issue with this setup unless I move the Plug statement outside this block but from your dot files this doesn't seem to be the issue. 

Based on a quick search, maybe there is some `runtimepath` issue?

**Comment by bastienboutonnet** [comment]
Hey @rmehri01 thanks for trying this out and sorry for the delay. Hm yeah I'm gonna have to see what could be messing with it. Probably means I should just nuke other plugins or so one by one. What was the quick search you got? Maybe it can point me in the right direction.

**Comment by rmehri01** [comment]
No problem, I just searched for `E185: Cannot find color scheme` and `vim plug colorscheme not found` and get the following for example:

- https://stackoverflow.com/questions/40077211/e185-cannot-find-color-scheme
- https://github.com/junegunn/vim-plug/issues/105#issuecomment-103479298

Maybe a way to test it is after you install onenord you can try finding the file `onenord.lua` and see if it's in your `runtimepath`? 

For example:
```
λ  fd -H onenord.lua
autoload/plugged/onenord.nvim/colors/onenord.lua
autoload/plugged/onenord.nvim/lua/lualine/themes/onenord.lua
```

And `:set runtimepath?` gives:
```
runtimepath=~/.config/nvim,~/.config/nvim/autoload/plugged/onenord.nvim,/etc/xdg/nvim,~/.local/share/nvim/site,~/.local/share/nvim/site/pack
/*/start/*,/usr/local/share/nvim/site,/usr/share/nvim/site,/usr/local/Cellar/neovim/HEAD-29cec32/share/nvim/runtime,/usr/local/Cellar/neovim/H
EAD-29cec32/share/nvim/runtime/pack/dist/opt/matchit,/usr/local/Cellar/neovim/HEAD-29cec32/lib/nvim,/usr/share/nvim/site/after,/usr/local/shar
e/nvim/site/after,~/.local/share/nvim/site/after,/etc/xdg/nvim/after,~/.config/nvim/after 
```

**Comment by bastienboutonnet** [comment]
Thanks a lot for the pointers. Somehow all looks good with the path (i.e. it's in there) but still it cannot find it.

But I guess this doesn't seem like it's a bug with your package so I guess we should probably close it so it doesn't bother you. I'll have to dig a bit more and maybe test it in a clean nvim setup.

Maybe I could also try the other plugin manager just for that, why not...

**Comment by rmehri01** [comment]
Sounds good, I'll close it for now but feel free to let me know if anything else happens when you get to trying it out!

**Comment by bastienboutonnet** [comment]
Yeah I'll keep you posted in this issue if I get it to work and understand what the issue was.
