### ISSUE TITLE
Fix highlight group links for Neovim 0.8

### ISSUE THREAD

**Issue by kristijanhusak** [rmehri01/onenord.nvim#50]
Nvim-treesitter updated how highlights are defined for Neovim 0.8.

https://github.com/nvim-treesitter/nvim-treesitter/pull/3656

Edit: This might be helpful https://github.com/Mofiqul/dracula.nvim/commit/9c17951049db9a09487467141aa0bdb00e4ce32c

**Comment by rmehri01** [comment]
Ah cool, thanks for letting me know! I'll work on it later today

**Comment by rmehri01** [comment]
I think this fixes it but let me know if something doesn't look right!

**Comment by cjhead** [comment]
> I think this fixes it but let me know if something doesn't look right!

Just tested it and it works great, thanks!

**Comment by rmehri01** [comment]
> Just tested it and it works great, thanks!

No problem, I'll close this for now then.

**Comment by appelgriebsch** [comment]
This update breaks compatibility with Neovim 0.7.x...

```
Error detected while processing nvim_exec() called at /Users/gerlaca1/.local/share/nvim/site/pack/packer/start/onenord.nvim/color
s/onenord.lua:0:
W18: Invalid character in group name
```

**Comment by kristijanhusak** [comment]
> This update breaks compatibility with Neovim 0.7.x...
> 
> ```
> Error detected while processing nvim_exec() called at /Users/gerlaca1/.local/share/nvim/site/pack/packer/start/onenord.nvim/color
> s/onenord.lua:0:
> W18: Invalid character in group name
> ```
> 
> ```
> packer.nvim: Error running config for onenord.nvim: /Users/gerlaca1/.config/nvim/lua/plugins/theme.lua:15: Vim(colorscheme):E5113: Error while calling lua chunk: ...site/pack/packer/start/onenord.nvim/lua/onenord/util.lua:14: Keyboard interrupt
> stack traceback:
> 	[C]: in function 'cmd'
> 	...site/pack/packer/start/onenord.nvim/lua/onenord/util.lua:14: in function 'highlight'
> 	...site/pack/packer/start/onenord.nvim/lua/onenord/util.lua:43: in function 'load'
> 	...site/pack/packer/start/onenord.nvim/lua/onenord/init.lua:19: in function 'load'
> 	...m/site/pack/packer/start/onenord.nvim/colors/onenord.lua:13: in main chunk
> ```

Requirement section did update: https://github.com/rmehri01/onenord.nvim#requirements

**Comment by kristijanhusak** [comment]
> I think this fixes it but let me know if something doesn't look right!

Everything works great, thanks!

**Comment by rmehri01** [comment]
> This update breaks compatibility with Neovim 0.7.x...

I think `nvim-treesitter` also mentions that it requires Neovim 0.8.0 or later, so I decided to do the same

**Comment by appelgriebsch** [comment]
Ok, just started upgrading to Neovim 0.8 in my setup as well. Thanks for your feedback.

**Comment by rmehri01** [comment]
Sure, I can do that :)
