### ISSUE TITLE
Highlight colors are different after updating highlight groups to nvim-0.8

### ISSUE THREAD

**Issue by FeiyouG** [rmehri01/onenord.nvim#52]
Hi, thank you for making this plugin, I really love it. 

Recently after the commit 98c64654375bc087e96bca08fd194066d778717c, many of the colors inside nvim became different from what they were before. Here are some screenshots:

Colors before the update:
<img width="666" alt="Screen Shot 2022-10-19 at 21 18 16" src="https://user-images.githubusercontent.com/33943746/196855374-928f58fe-bc93-4dd6-a68a-ffdc7d484645.png">

Colors after the update:
<img width="675" alt="Screen Shot 2022-10-19 at 21 17 28" src="https://user-images.githubusercontent.com/33943746/196855341-015092bd-58f3-4601-9459-1961818f161b.png">

I am unsure whether the changes were introduced by the tree-sitter or this plugin, but I found if I use a commit before this one 98c64654375bc087e96bca08fd194066d778717c, the colors won't change.

**Comment by rmehri01** [comment]
Hi! Check out #50 and the latest release, basically `nvim-treesitter` introduced a breaking change for removing `TS*` highlight groups and I made a tag for 0.7 before the commit you specified

**Comment by FeiyouG** [comment]
Hi @rmehri01, with `nvim-treesitter` removed TS* support, why does it change the color, say the parentheses, from yellow to red? It would change the way plugins interact with the tree-sitter, but the theme color for each token shouldn't change, right?
