### ISSUE TITLE
colors/onenord.vim missing

### ISSUE THREAD

**Issue by cwaldbieser** [rmehri01/onenord.nvim#58]
I think if you create an empty file or one with just a comment for "colors/onenord.vim", then the color scheme will show up is the color scheme completions.

I use the colorscheme switcher plugin, and that definitely won't pick up this scheme because of the missing file.

**Comment by rmehri01** [comment]
Hey, what colorscheme switcher are you using? That way I can test it out since it seems to show up for me when doing `:colorscheme` and `:Telescope colorscheme`.

**Comment by cwaldbieser** [comment]
https://github.com/xolox/vim-colorscheme-switcher

**Comment by rmehri01** [comment]
Hmm, adding an empty file doesn't seem to work for me, did it for you? Replacing `colors/onenord.lua` with `colors/onenord.vim` does seem to do it for me. It also seems like the plugin doesn't work for other lua colorschemes like tokyonight, I'm guessing for the same reason.

**Comment by cwaldbieser** [comment]
Well, the plugin lets you configure a helper command rather than "colorscheme".  I guess that's because some of the newer color schemes, especially lua based ones, have different ways to setup/initialize.  However, the switcher code looks like it is just looking in the "colors" folders for .vim files to get a list of color schemes.

This is my [helper command](https://github.com/cwaldbieser/dotfiles/blob/primary/dotfiles/config/nvim/lua/user/colorschemes.lua).  I just put the empty "onenord.vim", the switcher finds it.  If I don't, the switcher doesn't find it.
I'm not sure how you're supposed to iterate over color schemes in neovim, so I'm not sure if the colorscheme plugin really is supposed to have a "colors/NAME.vim", by convention, or if that was just a fragile approach taken by the switcher plugin.  In the latter case, I could ask that plugin author to update the switcher code.

**Comment by rmehri01** [comment]
Ah I see, thank you for the clarifications! I see that in the [neovim documentation](https://neovim.io/doc/user/syntax.html#%3Ahighlight), both vim and lua files are allowed, `colors/{name}.(vim|lua)` so it might just be an issue of this plugin being originally written for vim and not neovim.

**Comment by rmehri01** [comment]
Closing for now since it seems like an issue with the plugin being written for vim and not neovim
