### ISSUE TITLE
Lightspeed colors seem off

### ISSUE THREAD

**Issue by jose-elias-alvarez** [rmehri01/onenord.nvim#6]
Some of the colors Onenord uses for [lightspeed.nvim](https://github.com/ggandor/lightspeed.nvim) cause issues when using the plugin. For example, Lightspeed highlights all of the unique characters in the viewport, but these are quite hard to see when using Onenord:

![Screen Shot 2021-11-03 at 12 18 02 PM](https://user-images.githubusercontent.com/54108223/140100615-f09ae0a8-d3fa-4b24-910f-60e5505e72ff.png)

For comparison, here's the same view when using the Nordfox theme from [nightfox.nvim](https://github.com/EdenEast/nightfox.nvim):

![Screen Shot 2021-11-03 at 12 18 16 PM](https://user-images.githubusercontent.com/54108223/140100695-bef78b77-9e41-4cca-ac0b-c8f6bd1ca3d3.png)

Likewise, the colors used when jumping are a bit confusing. Here, the first character indicates a match, and the second character indicates the character that will jump to that match, but they're so similar that it's hard to know which is which at a glance:

![Screen Shot 2021-11-03 at 12 18 34 PM](https://user-images.githubusercontent.com/54108223/140100994-70139afc-da82-43a9-8ff0-952220e9d341.png)

I think Nordfox doesn't modify these colors at all, so they're pretty ugly, but you can see that there's a lot of contrast between the first and second characters, which makes it easier to parse:

![Screen Shot 2021-11-03 at 12 18 56 PM](https://user-images.githubusercontent.com/54108223/140101093-982c56d6-4c7a-411d-8be4-9eb7951ae7a3.png)

I'd put in a PR, but I'm frankly inept when it comes to anything color-related. I saw that the author of Lightspeed just updated the [guidelines for color scheme integration](https://github.com/ggandor/lightspeed.nvim#guidelines-for-colorscheme-integrations), so maybe that could provide some guidance.

**Comment by rmehri01** [comment]
Hi again, sorry about this, I didn't know about the guidelines posted by the author so I just tried out something similar to Nord.nvim. I'll read it tonight and try to come up with something that's stylized but also fits the guidelines!

**Comment by jose-elias-alvarez** [comment]
No need to apologize, and thank you!

**Comment by rmehri01** [comment]
I had some time to look at it so it's definitely more usable now but I'm not sure about the colors either, for now it is just a toned down version of the original. Any thoughts?

Original:
<img width="1542" alt="Screen Shot 2021-11-03 at 11 27 06 AM" src="https://user-images.githubusercontent.com/52933714/140170659-f30be0e2-4abe-4ad8-b004-4373a2a8ff49.png">

Onenord:
<img width="1542" alt="Screen Shot 2021-11-03 at 12 00 39 PM" src="https://user-images.githubusercontent.com/52933714/140175457-ad076de4-1faa-4da7-b00b-b8b7b06e4961.png">

Fixed unique characters:
<img width="1542" alt="Screen Shot 2021-11-03 at 12 00 53 PM" src="https://user-images.githubusercontent.com/52933714/140175487-51a91c43-9a3d-43cf-b9db-4f2c07776820.png">

**Comment by jose-elias-alvarez** [comment]
Looks great IMO!

**Comment by rmehri01** [comment]
Alright thanks, I just pushed a commit so let me know if you still see any problems!

**Comment by jose-elias-alvarez** [comment]
Way easier to use. Thank you for the changes!
