### ISSUE TITLE
Update Docs!

### ISSUE THREAD

**Issue by brandeschi** [rmehri01/onenord.nvim#61]
Hi, I just wanted to let you know the docs for adding `custom_hightlights` should probably be updated. I just spent way too long trying to figure out why your example was not working to realize `tree-sitter` changed their highlight group names for Neovim 0.8... 😅 Or at least mention the potential conflict in the docs since you also have a tagged release for 0.7.

Thank you for this awesome theme btw!

**Comment by rmehri01** [comment]
Oh sorry about that, I should have searched through the repo for any `TS*` usages 😅 

And no problem, I'm glad you like it!
