### ISSUE TITLE
Missing hl groups for Lsp Saga

### ISSUE THREAD

**Issue by joeveiga** [rmehri01/onenord.nvim#62]
After the latest refactor in lsp saga, there are a few new highlight groups. Please see: https://github.com/glepnir/lspsaga.nvim/blob/main/lua/lspsaga/highlight.lua#L28

**Comment by rmehri01** [comment]
Hey, thanks for bringing this up! Yeah I saw that lspsaga had been updated recently, I'll try to get to it soon :)

**Comment by joeveiga** [comment]
Thanks!
