### ISSUE TITLE
Inconsistent colors from one version to another

### ISSUE THREAD

**Issue by Freyskeyd** [rmehri01/onenord.nvim#63]
Hello,

I've seen recent changes on that 71bdcdf105a8feb16cd5248b40e44c88832f75ca commit that put wrong colors on some part of code:

### before
![Screenshot 2023-02-13 at 12 41 35](https://user-images.githubusercontent.com/1394604/218448982-d65e2552-fd75-4455-8a1b-fceee155466a.png)

### after
![Screenshot 2023-02-13 at 12 42 06](https://user-images.githubusercontent.com/1394604/218449004-580ebdd6-e94c-4276-859c-db5f80a6f757.png)

How can I fix this to have the same colors than before?

thanks a lot !

**Comment by rmehri01** [comment]
Hi, sorry about that, I was trying to make it more consistent with treesitter for example when namespacing a function but in Rust the base syntax `Include` is also used for both the imports and uses vs treesitter using `@namespace` and `@struct`.

Base syntax before change:

<img width="383" alt="image" src="https://user-images.githubusercontent.com/52933714/218508928-a9bafc2b-e0a1-4dfd-ac67-30da732cb154.png">

Treesitter highlight:

<img width="389" alt="image" src="https://user-images.githubusercontent.com/52933714/218509758-5dcac2c3-4420-4e92-b7b1-7c078f2fa364.png">

Base syntax after change:

<img width="401" alt="image" src="https://user-images.githubusercontent.com/52933714/218508601-250e70e6-f0e4-4c20-b4d2-ad575cc29c99.png">

You can always change custom highlights doing the following:

```lua
      local colors = require("onenord.colors").load()
      require("onenord").setup({
        custom_highlights = {
          Include = { fg = colors.blue },
        },
      })
```

This one just changes the namespaces but feel free to customize anything else to your liking 😄

**Comment by rmehri01** [comment]
Okay sorry for the delay, I've decided to revert these changes since I guess it's okay that the two aren't perfectly consistent and there are other ways to fix the semantic token highlighting.

**Comment by Freyskeyd** [comment]
This issue seems to need to be re-open as I see some new issues on some code highlight

**Comment by rmehri01** [comment]
Hi, did you upgrade to neovim 0.9 recently? If so, this is probably due to LSP semantic tokens. You can check it out under `:h lsp-semantic-highlight` or disable it using something like `client.server_capabilities.semanticTokensProvider = nil` in your `on_attach`.
