### ISSUE TITLE
Add semantic highlights support

### ISSUE THREAD

**Issue by wcampbell0x2a** [rmehri01/onenord.nvim#64]
This uses neovim nightly

Example: https://github.com/rebelot/kanagawa.nvim/commit/57815655d7f7bc0b78c8a5b45de38db28aabfd58

**Comment by rmehri01** [comment]
Hey, thanks for bringing this up, I saw it recently so I'll try to put up a nightly branch soon!

**Comment by rmehri01** [comment]
Alright feel free to try this out and let me know what you think 😄

**Comment by wcampbell0x2a** [comment]
Cool, works!

Even adds documentation code example highlighting for rust code, pretty sweet.
