### ISSUE TITLE
Colorscheme light/dark

### ISSUE THREAD

**Issue by lvstb** [rmehri01/onenord.nvim#67]
Is there a way to make the light variant of the colorscheme visible in the list of colorschemes?
Like for example catpuccing where you have 4 variants: catpuccing-mocha, catpuccin-latte.,...
It would be nice to have onenord, onenord-light.

Right now there is only onenord and depending of the config you give it (via theme = dark/light) it will be dark or light.

Reasoning behind this is that it would make it easy to switch between them depending the time of the day.

**Comment by rmehri01** [comment]
Hey! This is what we had before but I wasn't sure of the interactions with `background` at the time but I think this is doable, it seems that tokyonight does something similar.

**Comment by lvstb** [comment]
Hey!
Great to see you responding and commiting this quick :-D
Is it possible there is still something not 100%
Im now able to quickly switch between dark and light (thanks), but for example my telescope and wilder menu is not switching to light but remains dark (i did the test with other themes and there this just works).

**Comment by lvstb** [comment]
Indeed, opening a new telescope window or the autocomplette window,.... they all stay in the dark theme even when opening a new one.

**Comment by lvstb** [comment]
You are correct, it was my config. 
Thanks!

**Comment by rmehri01** [comment]
No problem! Feel free to let me know if you think the customizations per theme would be helpful or not 😄

**Comment by hakkeroid** [comment]
> 
> ```lua
>   custom_highlights = {
>     dark = { ... },
>     light = { ... },
>   },
> ```

@rmehri01 I don't mean to necrobump an already closed issue. However, since you had this feature on your mind already I would like to add my support for it. The dark background color is a bit too light for my taste and I can't override it without breaking the light version as well.

**Comment by rmehri01** [comment]
Hey! I just pushed a commit that should make this work but let me know if you run into any trouble 😄

**Comment by hakkeroid** [comment]
Man, that was fast and works like a charm. Thank you a lot!
