### ISSUE TITLE
Nvim-treesitter capture name changes

### ISSUE THREAD

**Issue by kristijanhusak** [rmehri01/onenord.nvim#80]
Hi,

I just got a notification from nvim-treesitter that some of the capture names changed (https://github.com/nvim-treesitter/nvim-treesitter/issues/2293#issuecomment-1900679583)
This commit lists all the changes https://github.com/nvim-treesitter/nvim-treesitter/commit/1ae9b0e4558fe7868f8cda2db65239cfb14836d0

Not sure how many changes are needed, just opening up the issue upfront so we are aware of it.

**Comment by rmehri01** [comment]
Thanks again for letting me know so quickly! I've pushed a commit that should fix it, let me know if you run into any troubles.

**Comment by kristijanhusak** [comment]
Looks good! Thanks for addressing it so quickly!
