### ISSUE TITLE
Problems with Lspsaga integration

### ISSUE THREAD

**Issue by Uaitt** [rmehri01/onenord.nvim#86]
Hello,
I am trying to set up the Lspsaga integration for this theme:

my `.config/nvim/lua/plugins/lspsaga.lua`:
```lua
return {
  "glepnir/lspsaga.nvim",
  dependencies = {
    "nvim-treesitter/nvim-treesitter",
  },
  lazy = false,
  config = function()
    require("lspsaga").setup({
      ui = {
        kind = require("onenord.integrations.lspsaga").custom_kind(),
      },
    })
  end,
}
```

When I open neovim I get this:
![Screenshot 2024-05-28 at 12 33 11](https://github.com/rmehri01/onenord.nvim/assets/97030518/636401b3-098b-4fb2-ac8c-520f569eabb6)

If I replace the setup table with an empty table Neovim does not give any error.

A few more infos:
```
NVIM v0.10.0
LuaJIT 2.1.1713484068

lspsaga
commit 59d4648
```

not sure if I'm doing something wrong since I am Neovim newbie, but hope somebody can help 😄.

**Comment by rmehri01** [comment]
Hey, I just removed this integration since it's no longer needed. It used to be the case that the colors wouldn't show up without it but that has been fixed since, sorry for the confusion 😅

**Comment by Uaitt** [comment]
Thanks @rmehri01! I think you can close this issue now 😃.
