### ISSUE TITLE
Add support for PmenuMatch and PmenuMatchSel

### ISSUE THREAD

**Issue by kristijanhusak** [rmehri01/onenord.nvim#88]
Hi,

In new versions of Neovim 2 new HL groups were added: `PmenuMatch` and `PmenuMatchSel`. PR https://github.com/neovim/neovim/pull/29311

To make it similar to `cmp`, I suggest using the same color + float background:

```lua
      PmenuMatch = { fg = colors.blue, bg = colors.float, style = 'bold' },
      PmenuMatchSel = { fg = colors.blue, bg = colors.selection, style = 'bold' },
```

**Comment by rmehri01** [comment]
Hey thank you again for the early reminder, I just tried it out and it looks great!
