### ISSUE TITLE
Can overrdie background 

### ISSUE THREAD

**Issue by JoseConseco** [rmehri01/onenord.nvim#9]
I'm not sure what I'm doing wrong:
![image](https://user-images.githubusercontent.com/13521338/143839028-d42b9140-8c13-4f86-b1a4-8afb56efc011.png)
It should make the background black right?

**Comment by rmehri01** [comment]
Hi, have you updated onenord recently because I think I fixed a few bugs related to configuration.

**Comment by JoseConseco** [comment]
Ok, by bad.  I had two  themes : nightfox and onenord  -  both are using setup() functions for customization. 
Disabling nigthfox  helped to load onenord.setup() with updated background color . 
I guess there is no way to customize highlights of onenord unless it is loaded as 'main/startup' colorsheme.

**Comment by rmehri01** [comment]
Ah I see, yeah I recently switched to a config structure similar to nightfox since it seems to work better for me. I could try to find a way to get them to work together if you think that would be helpful?

**Comment by JoseConseco** [comment]
Well I think if maybe you could use  ColorScheme autocmd
`		autocmd ColorScheme * call xxxx
So that when users changes colorscheme, onenord will read updated setup() ?  Not sure if this can fix the issue...

**Comment by rmehri01** [comment]
I just pushed a commit, can you try out your old setup with nightfox? It seems to work for me.

**Comment by rmehri01** [comment]
I think that could work, what I did was essentially just make a new field for `config.options` like nightfox does and then mutate that with `setup` so that it can still be used when switching themes.

**Comment by JoseConseco** [comment]
Thanks it works now.  Great theme btw.

**Comment by rmehri01** [comment]
> Thanks it works now. Great theme btw.

Awesome, thanks for testing it out! I'm glad you like it 😄
